name: Deploy NihonGO Master to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7926FABDB84446D982BBD084FDEF2AAE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8222663914DC41F48C34775315B1E5AD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ACB69DF16DBB47C39015ACB9EC59CF81 }}

      - name: Deploy NihonGO Master
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kisejapan'
          slot-name: 'Production'
          package: './Site japones estudo'
